spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/d03h/spring-netflix-oss.git
          searchPaths: config-repo/
          clone-on-start: true
          username: d03h
          password: V@lmiki@2020
          default-label: main
server:
  port: 8888
